# my own $HOME/.config/mayi.ini as an example

[*]
# trust the OS to handle permissions properly, because sometimes a program need to write to /run for example
/nix/.* = allow
/etc/.* = allow
/run/.* = allow
/var/.* = allow
/usr/.* = allow
/lib.* = allow
/bin/.* = allow
/tmp/.* = allow
/run/.* = allow
/proc/.* = allow
/sys.* = allow
/dev/.* = allow

# many processes try to read it
$HOME/\.nix-profile/.* = read
$HOME/\.local/.* = allow
$HOME/\.config/.* = allow
$HOME/\.icons/.* = allow
$HOME/\.cache/.* = allow
$HOME/\.zplug/.* = allow
$HOME/dotfiles/.* = read
$HOME/\.alsoftrc = read
$HOME/\.drirc = read
$HOME/\.XCompose = read
$HOME/\.zshenv = read
$HOME/\.zshrc = read
$HOME/\.zcompdump = read
$HOME/\.local = read

dirs = read  # can list any directory, but not read the underlying files

[bash]
$HOME = read
$HOME/\.bashrc = allow
$HOME/\.bash_history.* = allow
$HOME/\.inputrc = allow
$HOME/Git/.* = allow
$PWD = allow

[emacs]
$HOME = read
$HOME/\.gitconfig = read
$HOME/\.emacs.* = allow
$HOME/dotfiles.* = allow
$HOME/Git/.* = allow

[nvim]
$HOME/\.terminfo/.* = read
$HOME/Git/.* = allow

[dolphin]
/ = read
$HOME = read
$HOME/[^.].* = read
$HOME/\.hidden = read
$HOME/\.pulse/.* = read