# my own $HOME/.config/mayi.ini as an example

[*]
# trust the OS to handle permissions properly, because sometimes a program need to write to /run for example
/nix/.* = read write
/etc/.* = read write
/run/.* = read write
/var/.* = read write
/usr/.* = read write
/lib.* = read write
/bin/.* = read write
/tmp/.* = read write
/run/.* = read write
/proc/.* = read write
/sys.* = read write
/dev/.* = read write

# many processes try to read it
$HOME/\.nix-profile/.* = read
$HOME/\.local/.* = read write
$HOME/\.config/.* = read write
$HOME/\.icons/.* = read write
$HOME/\.cache/.* = read write
$HOME/\.zplug/.* = read write
$HOME/dotfiles/.* = read
$HOME/\.alsoftrc = read
$HOME/\.drirc = read
$HOME/\.XCompose = read
$HOME/\.zshenv = read
$HOME/\.zshrc = read
$HOME/\.zcompdump = read
$HOME/\.local = read

# can list the current directory, but that doesn't mean being able to read the files inside PWD
$PWD = read


[emacs]
$HOME = read
$HOME/.gitconfig = read
$HOME/\.emacs.* = read write
$HOME/dotfiles/\.emacs\.d.* = read write
$HOME/Git/.* = read write
